package es.uma.informatica.sii.web.tests;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import org.junit.After;
import org.junit.Before;
import org.junit.FixMethodOrder;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.runners.MethodSorters;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import es.uma.informatica.sii.anotaciones.Requisitos;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class AsignaturasIntegracion {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	private static String URL_ASIGNATURAS = "/home/alumno/git/grupoE/grupoE-ejb/DATOS/asignaturas.xlsx";

	@Before
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
		driver.manage().timeouts().implicitlyWait(5, TimeUnit.SECONDS);
		driver.manage().timeouts().pageLoadTimeout(1, TimeUnit.MINUTES);
		driver.manage().window().setSize(new Dimension(1440, 900));
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	// Diseño de pagina con elementos principales para importar y listar asignaturas
	@Requisitos({ "RF1.1" })
	@Test
	public void test11DisenoInicialAsignaturas() {
		System.out.println("TEST1");
		driver.get("http://localhost:8080/grupoE-war/faces/asignaturas.xhtml");
		assertThat(driver.getTitle(), is("Asignaturas"));
		assertThat(driver.findElement(By.id("titulo_listado")).getText(), is("Listado de asignaturas"));
		{
			List<WebElement> elements = driver.findElements(By.id("j_idt18:tipo"));
			assert (elements.size() > 0);
		}
		{
			List<WebElement> elements = driver.findElements(By.id("j_idt16:file-id"));
			assert (elements.size() > 0);
		}
		{
			List<WebElement> elements = driver.findElements(By.id("j_idt16:upload"));
			assert (elements.size() > 0);
		}
		{
			List<WebElement> elements = driver.findElements(By.id("j_idt16:borrarTodo"));
			assert (elements.size() > 0);
		}
		assertThat(driver.findElement(By.cssSelector(".formatoHeader:nth-child(1)")).getText(), is("Referencia"));
		assertThat(driver.findElement(By.cssSelector(".formatoHeader:nth-child(2)")).getText(), is("Código"));
		assertThat(driver.findElement(By.cssSelector(".formatoHeader:nth-child(3)")).getText(), is("Curso"));
		assertThat(driver.findElement(By.cssSelector(".formatoHeader:nth-child(4)")).getText(), is("Nombre"));
		assertThat(driver.findElement(By.cssSelector(".formatoHeader:nth-child(5)")).getText(), is("Cuatrimestre"));
		assertThat(driver.findElement(By.cssSelector(".formatoHeader:nth-child(6)")).getText(), is("C.T"));
		assertThat(driver.findElement(By.cssSelector(".formatoHeader:nth-child(7)")).getText(), is("C.P"));
		assertThat(driver.findElement(By.cssSelector(".formatoHeader:nth-child(8)")).getText(), is("Grupos asignados"));
	}

	// Importar asignaturas sin indicar archivo dbe devolver un error
	@Requisitos({ "RF1.1" })
	@Test
	public void test12ImportarAsignaturasFicheroErroneo() {
		driver.get("http://localhost:8080/grupoE-war/faces/asignaturas.xhtml");
		driver.findElement(By.id("j_idt16:upload")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(
					ExpectedConditions.textToBe(By.id("j_idt16:mensaje_subida"), "Error de importación. Sin cambios"));
		}
		assertThat(driver.getTitle(), is("Asignaturas"));
	}

	// Importar asignaturas correctamente debe crear 81 asignaturas para GII con
	// todos sus campos correctamente
	@Requisitos({ "RF1.1" })
	@Test
	public void test13ImportarAsignaturasCorrectamente() {
		driver.get("http://localhost:8080/grupoE-war/faces/asignaturas.xhtml");
		driver.findElement(By.cssSelector("#j_idt16\\3A file-id")).sendKeys(URL_ASIGNATURAS);
		driver.findElement(By.id("j_idt16:upload")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt16:mensaje_subida"), "Importación correcta"));
		}
		assertThat(driver.findElement(By.id("j_idt25:0:referencia")).getText(), is("50658"));
		driver.findElement(By.id("editar_asignatura")).click();
		assertThat(driver.findElement(By.id("j_idt25:0:nombre")).getText(), is("Cálculo para la Computación"));
		{
			List<WebElement> elements = driver.findElements(By.id("j_idt25:0:j_idt43:eliminar"));
			assert (elements.size() > 0);
		}
		{
			List<WebElement> elements = driver.findElements(By.id("editar_asignatura"));
			assert (elements.size() > 0);
		}
		{
			List<WebElement> elements = driver.findElements(By.id("j_idt25:81:referencia"));
			assert (elements.size() > 0);
		}
	}

	// Listar asignaturas importadas para cada grado debe dar la informacion
	// relativa a dicho grado
	@Requisitos({ "RF1.1" })
	@Test
	public void test14FiltrosAsignaturasPorGrados() {
		driver.get("http://localhost:8080/grupoE-war/faces/asignaturas.xhtml");
		assertThat(driver.findElement(By.id("j_idt25:0:referencia")).getText(), is("50658"));
		{
			WebElement dropdown = driver.findElement(By.id("j_idt18:tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Ingeniería del Software (1042)']")).click();
		}
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt25:0:referencia"), "51138"));
		}
		{
			WebElement dropdown = driver.findElement(By.id("j_idt18:tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Ingeniería de Computadores (1043)']")).click();
		}
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt25:0:referencia"), "51673"));
		}
		{
			WebElement dropdown = driver.findElement(By.id("j_idt18:tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Ingeniería de la Salud (1056)']")).click();
		}
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt25:0:referencia"), "53008"));
		}
		{
			WebElement dropdown = driver.findElement(By.id("j_idt18:tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Doble Grado II+Matemáticas (1073)']")).click();
		}
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt25:0:referencia"), "51487"));
		}
	}

	// Si no se modifica ningun dato de la asignatura, esta debe mostar los datos
	// anteriores
	@Requisitos({ "RF1.2" })
	@Test
	public void test15ModificarNingunDatoAsignatura() {
		driver.get("http://localhost:8080/grupoE-war/faces/asignaturas.xhtml");
		assertThat(driver.findElement(By.id("j_idt25:3:creditos_teoricos")).getText(), is("6.0"));
		assertThat(driver.findElement(By.id("j_idt25:3:creditos_practicos")).getText(), is("0.0"));
		driver.findElement(By.cssSelector(".formatoFilaPar:nth-child(4) #editar_asignatura")).click();
		driver.findElement(By.id("j_idt25:3:user-form:enviar")).click();
		assertThat(driver.findElement(By.id("j_idt25:3:creditos_teoricos")).getText(), is("6.0"));
		assertThat(driver.findElement(By.id("j_idt25:3:creditos_practicos")).getText(), is("0.0"));
	}

	// Modificar datos de las asignaturas deben verse modificadas sus respectivas
	// columnas
	@Requisitos({ "RF1.2" })
	@Test
	public void test16ModificarDatosAsignatura() {
		driver.get("http://localhost:8080/grupoE-war/faces/asignaturas.xhtml");
		assertThat(driver.findElement(By.id("j_idt25:3:nombre")).getText(), is("Fundamentos de la Programación"));
		assertThat(driver.findElement(By.id("j_idt25:3:creditos_teoricos")).getText(), is("6.0"));
		assertThat(driver.findElement(By.id("j_idt25:3:creditos_practicos")).getText(), is("0.0"));
		driver.findElement(By.cssSelector(".formatoFilaPar:nth-child(4) #editar_asignatura")).click();
		driver.findElement(By.id("j_idt25:3:user-form:teoricos")).sendKeys("100");
		driver.findElement(By.id("j_idt25:3:user-form:practicos")).sendKeys("200");
		driver.findElement(By.id("j_idt25:3:user-form:enviar")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt25:3:creditos_teoricos"), "100.0"));
		}
		assertThat(driver.findElement(By.id("j_idt25:3:creditos_teoricos")).getText(), is("100.0"));
		assertThat(driver.findElement(By.id("j_idt25:3:creditos_practicos")).getText(), is("200.0"));
		{
			WebElement dropdown = driver.findElement(By.id("j_idt18:tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Ingeniería de la Salud (1056)']")).click();
		}
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt25:0:referencia"), "53008"));
		}
		assertThat(driver.findElement(By.id("j_idt25:0:nombre")).getText(), is("Bioquímica Estructural"));
		assertThat(driver.findElement(By.id("j_idt25:0:creditos_teoricos")).getText(), is("6.0"));
		assertThat(driver.findElement(By.id("j_idt25:0:creditos_practicos")).getText(), is("0.0"));
		driver.findElement(By.id("editar_asignatura")).click();
		driver.findElement(By.id("j_idt25:0:user-form:teoricos")).sendKeys("25");
		driver.findElement(By.id("j_idt25:0:user-form:practicos")).sendKeys("3.65");
		driver.findElement(By.id("j_idt25:0:user-form:enviar")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt25:0:creditos_teoricos"), "25.0"));
		}
		assertThat(driver.findElement(By.id("j_idt25:0:nombre")).getText(), is("Bioquímica Estructural"));
		assertThat(driver.findElement(By.id("j_idt25:0:creditos_teoricos")).getText(), is("25.0"));
		assertThat(driver.findElement(By.id("j_idt25:0:creditos_practicos")).getText(), is("3.65"));
	}

	// Se debe permitir modificar los grupos asignados a cada matricula mediante un
	// selector personalizado que muestre los grupos disponibles en el curso y
	// titulacion donde nos encontramos
	@Requisitos({ "RF1.4" })
	@Test
	public void test17AsignarGruposAsignatura() {
		driver.get("http://localhost:8080/grupoE-war/faces/asignaturas.xhtml");
		driver.findElement(By.cssSelector(".formatoFilaImpar:nth-child(3) #editar_asignatura")).click();
		driver.findElement(By.cssSelector("#j_idt25\\3A 2\\3Auser-form\\3Agrupos_imparticion td:nth-child(2) > label"))
				.click();
		driver.findElement(By.cssSelector("#j_idt25\\3A 2\\3Auser-form\\3Agrupos_imparticion td:nth-child(4) > label"))
				.click();
		driver.findElement(By.id("j_idt25:2:user-form:enviar")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt25:2:grupos_asignados"), "(1 B) (1 D)"));
		}
		assertThat(driver.findElement(By.id("j_idt25:2:grupos_asignados")), is("(1 B) (1 D)"));
		driver.findElement(By.cssSelector(".formatoFilaImpar:nth-child(3) #editar_asignatura")).click();
		driver.findElement(By.cssSelector("#j_idt25\\3A 2\\3Auser-form\\3Agrupos_imparticion td:nth-child(2) > label"))
				.click();
		driver.findElement(By.id("j_idt25:2:user-form:enviar")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt25:2:grupos_asignados"), "(1 D)"));
		}
		assertThat(driver.findElement(By.id("j_idt25:2:grupos_asignados")), is("(1 D)"));
	}

	// Borrar una asignatura deja de mostrarla en la vista
	@Requisitos({ "RF1.3" })
	@Test
	public void test18BorrarAsignatura() {
		driver.get("http://localhost:8080/grupoE-war/faces/asignaturas.xhtml");
		driver.findElement(By.id("j_idt25:0:j_idt43:eliminar")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt25:0:referencia"), "50659"));
		}
		assertThat(driver.findElement(By.id("j_idt25:80:referencia")).getText(), is("51045"));
		{
			WebElement dropdown = driver.findElement(By.id("j_idt18:tipo"));
			dropdown.findElement(By.xpath("//option[. = 'Ingeniería de Computadores (1043)']")).click();
		}
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt25:1:referencia"), "51674"));
		}
		driver.findElement(By.id("j_idt25:1:j_idt43:eliminar")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt25:1:referencia"), "51675"));
		}
	}

	// Borrar todas las asignaturas deja la pagina sin dingun dato
	@Requisitos({ "RF1.3" })
	@Test
	public void test19VaciarDatosAsignaturas() {
		driver.get("http://localhost:8080/grupoE-war/faces/asignaturas.xhtml");
		driver.findElement(By.id("j_idt16:borrarTodo")).click();
		driver.findElement(By.id("j_idt16")).click();
		{
			WebDriverWait wait = new WebDriverWait(driver, 30);
			wait.until(ExpectedConditions.textToBe(By.id("j_idt16:mensaje_subida"), "Borrado correcto"));
		}
		assertThat(driver.getTitle(), is("Asignaturas"));
		{
			List<WebElement> elements = driver.findElements(By.id("j_idt25:0:referencia"));
			assert (elements.size() == 0);
		}
	}
}
